Running launcher /home/runner/work/bundler-test-executor/bundler-test-executor/launchers/voltaire-bundler-launcher.sh, name=Voltaire-Bundler
0.13: Pulling from sherifahmed990/voltaire-bundler
Digest: sha256:56a01f0ce7879b9f232440b896e41eecd406f22ea15be487ed5b77346c1e5fce
Status: Downloaded newer image for sherifahmed990/voltaire-bundler:0.13
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ethereum/client-go:release-1.10
 ---> c16c2e0da325
Step 2/2 : ENTRYPOINT geth       --verbosity 1       --http.vhosts '*,localhost,host.docker.internal'       --http       --http.api personal,eth,net,web3,debug       --http.corsdomain '*'       --http.addr "0.0.0.0"       --nodiscover --maxpeers 0 --mine       --networkid 1337       --dev       --allow-insecure-unlock       --rpc.allow-unprotected-txs       --dev.gaslimit 20000000
 ---> Using cache
 ---> e8f7becad0fb
Successfully built e8f7becad0fb
Successfully tagged voltaire-bundler_geth-dev:latest
waiting for bundler to start
Timed-out waiting for http://localhost:3000/rpc
yarn run v1.22.19
$ ./scripts/hh-wrapper deploy --network localhost
Nothing to compile
No need to generate any newer typings.
==entrypoint addr= 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
deploying "SimpleAccountFactory" (tx: 0x282222249eef963956428354b771b6b56ca83e6143dac46c4f181739e64dd2a0)...: deployed at 0x9406Cc6185a346906296840746125a0E44976454 with 2799271 gas
==SimpleAccountFactory addr= 0x9406Cc6185a346906296840746125a0E44976454
Done in 2.24s.
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/runner/work/bundler-test-executor/bundler-test-executor/bundler-spec-tests
plugins: web3-5.31.1
collected 114 items / 1 skipped

tests/bundle/test_bundle.py .........                                    [  7%]
tests/bundle/test_codehash.py .                                          [  8%]
tests/bundle/test_storage_rules.py ....................................F [ 41%]
FF.FFFFFFF                                                               [ 50%]
tests/opbanning/test_op_banning.py ..................................... [ 82%]
........                                                                 [ 89%]
tests/rpc/test_eth_chainId.py .                                          [ 90%]
tests/rpc/test_eth_estimateUserOperationGas.py ...                       [ 92%]
tests/rpc/test_eth_getUserOperationByHash.py ..                          [ 94%]
tests/rpc/test_eth_getUserOperationReceipt.py ..                         [ 96%]
tests/rpc/test_eth_sendUserOperation.py ...                              [ 99%]
tests/rpc/test_eth_supportedEntryPoints.py .                             [100%]

=================================== FAILURES ===================================
_________________ test_rule[unstaked][account][no_storage][ok] _________________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=153)
______________ test_rule[unstaked][account][account_storage][ok] _______________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=155)
_________ test_rule[unstaked][account][account_reference_storage][ok] __________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=157)
______ test_rule[unstaked][account][account_reference_storage_struct][ok] ______
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=161)
_____________ test_rule[unstaked][account][external_storage][drop] _____________
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:25: in assert_error
    assert_rpc_error(response, response.message, RPCErrorCode.BANNED_OPCODE)
tests/utils.py:103: in assert_rpc_error
    assert response.code == code
E   AssertionError: assert -32521 == <RPCErrorCode.BANNED_OPCODE: -32502>
E    +  where -32521 = Error(code=-32521, message='execution reverted', data=None, id=163).code
__________________ test_rule[staked][account][no_storage][ok] __________________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=165)
_______________ test_rule[staked][account][account_storage][ok] ________________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=167)
__________ test_rule[staked][account][account_reference_storage][ok] ___________
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=169)
_______ test_rule[staked][account][account_reference_storage_struct][ok] _______
tests/bundle/test_storage_rules.py:19: in assert_ok
    assert response.result
E   AttributeError: 'Error' object has no attribute 'result'

The above exception was the direct cause of the following exception:
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:21: in assert_ok
    raise Exception(f"expected result object, got:\n{response}") from exc
E   Exception: expected result object, got:
E   Error(code=-32521, message='execution reverted', data=None, id=171)
______________ test_rule[staked][account][external_storage][drop] ______________
tests/bundle/test_storage_rules.py:320: in test_rule
    case.assert_func(response)
tests/bundle/test_storage_rules.py:25: in assert_error
    assert_rpc_error(response, response.message, RPCErrorCode.BANNED_OPCODE)
tests/utils.py:103: in assert_rpc_error
    assert response.code == code
E   AssertionError: assert -32521 == <RPCErrorCode.BANNED_OPCODE: -32502>
E    +  where -32521 = Error(code=-32521, message='execution reverted', data=None, id=173).code
=============================== warnings summary ===============================
tests/bundle/test_codehash.py::test_codehash_changed[]
  /home/runner/work/bundler-test-executor/bundler-test-executor/bundler-spec-tests/.venv/lib/python3.10/site-packages/web3/contract.py:1190: UserWarning: The log with transaction hash: HexBytes('0x100b346cc968846c335b40ee614d6c0368618412159cd383874ab7ec579536dd') and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
    warnings.warn(

tests/bundle/test_codehash.py::test_codehash_changed[]
  /home/runner/work/bundler-test-executor/bundler-test-executor/bundler-spec-tests/.venv/lib/python3.10/site-packages/web3/contract.py:1190: UserWarning: The log with transaction hash: HexBytes('0xad4ce46d5b2ff5b595b4b9820848acc7f3db25f79acacbf33c355283cc5565fb') and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
    warnings.warn(

tests/bundle/test_codehash.py::test_codehash_changed[]
  /home/runner/work/bundler-test-executor/bundler-test-executor/bundler-spec-tests/.venv/lib/python3.10/site-packages/web3/contract.py:1190: UserWarning: The log with transaction hash: HexBytes('0xeaf0523a75a86e382e21eb0adf1410a87f8dbe16771c891cda176166c5bde11b') and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
    warnings.warn(

tests/bundle/test_codehash.py::test_codehash_changed[]
  /home/runner/work/bundler-test-executor/bundler-test-executor/bundler-spec-tests/.venv/lib/python3.10/site-packages/web3/contract.py:1190: UserWarning: The log with transaction hash: HexBytes('0x74f5c123147dc8de4ba17dff79627f43907932ee1394bcd5e235445bfed483ff') and logIndex: 0 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================== PASSES ====================================
- generated xml file: /home/runner/work/bundler-test-executor/bundler-test-executor/build/out/voltaire-bundler-launcher.xml -
=========================== short test summary info ============================
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[only_priority_fee_bump]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[only_max_fee_bump]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[with_same_fee]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[with_less_fee]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[fee_bump_below_threshold]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[fee_bump_at_threshold]
PASSED tests/bundle/test_bundle.py::test_bundle_replace_op[fee_bump_above_threshold]
PASSED tests/bundle/test_bundle.py::test_max_allowed_ops_unstaked_sender[]
PASSED tests/bundle/test_bundle.py::test_max_allowed_ops_staked_sender[]
PASSED tests/bundle/test_codehash.py::test_codehash_changed[]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][no_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][reference_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][reference_storage_struct][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][account_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][account_reference_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][account_reference_storage_struct][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][account_reference_storage_init_code][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][context][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][paymaster][external_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][no_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][reference_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][reference_storage_struct][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][account_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][account_reference_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][account_reference_storage_struct][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][account_reference_storage_init_code][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][context][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][paymaster][external_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][no_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][reference_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][reference_storage_struct][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][account_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][account_reference_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][account_reference_storage_struct][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][factory][external_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][no_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][reference_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][reference_storage_struct][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][account_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][account_reference_storage][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][account_reference_storage_struct][ok]
PASSED tests/bundle/test_storage_rules.py::test_rule[staked][factory][external_storage][drop]
PASSED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][account_reference_storage_init_code][drop]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[GAS]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[NUMBER]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[TIMESTAMP]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[COINBASE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[DIFFICULTY]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[BASEFEE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[GASLIMIT]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[GASPRICE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[SELFBALANCE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[BALANCE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[ORIGIN]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[BLOCKHASH]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[CREATE]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[CREATE2]
PASSED tests/opbanning/test_op_banning.py::test_account_banned_opcode[SELFDESTRUCT]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[GAS]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[NUMBER]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[TIMESTAMP]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[COINBASE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[DIFFICULTY]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[BASEFEE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[GASLIMIT]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[GASPRICE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[SELFBALANCE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[BALANCE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[ORIGIN]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[BLOCKHASH]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[CREATE]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[CREATE2]
PASSED tests/opbanning/test_op_banning.py::test_paymaster_banned_opcode[SELFDESTRUCT]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[GAS]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[NUMBER]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[TIMESTAMP]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[COINBASE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[DIFFICULTY]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[BASEFEE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[GASLIMIT]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[GASPRICE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[SELFBALANCE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[BALANCE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[ORIGIN]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[BLOCKHASH]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[CREATE]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[CREATE2]
PASSED tests/opbanning/test_op_banning.py::test_factory_banned_opcode[SELFDESTRUCT]
PASSED tests/rpc/test_eth_chainId.py::test_eth_chainId[]
PASSED tests/rpc/test_eth_estimateUserOperationGas.py::test_eth_estimateUserOperationGas[]
PASSED tests/rpc/test_eth_estimateUserOperationGas.py::test_eth_estimateUserOperationGas_execution_revert
PASSED tests/rpc/test_eth_estimateUserOperationGas.py::test_eth_estimateUserOperationGas_simulation_revert
PASSED tests/rpc/test_eth_getUserOperationByHash.py::test_eth_getUserOperationByHash[]
PASSED tests/rpc/test_eth_getUserOperationByHash.py::test_eth_getUserOperationByHash_error
PASSED tests/rpc/test_eth_getUserOperationReceipt.py::test_eth_getUserOperationReceipt[]
PASSED tests/rpc/test_eth_getUserOperationReceipt.py::test_eth_getUserOperationReceipt_error
PASSED tests/rpc/test_eth_sendUserOperation.py::test_eth_sendUserOperation[]
PASSED tests/rpc/test_eth_sendUserOperation.py::test_eth_sendUserOperation_revert
PASSED tests/rpc/test_eth_sendUserOperation.py::test_eth_sendUserOperation_invalid_signature
PASSED tests/rpc/test_eth_supportedEntryPoints.py::test_eth_supportedEntryPoints[]
SKIPPED [1] tests/bundle/test_stake_rules.py:12: Skipped
FAILED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][no_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=153)
FAILED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][account_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=155)
FAILED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][account_reference_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=157)
FAILED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][account_reference_storage_struct][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=161)
FAILED tests/bundle/test_storage_rules.py::test_rule[unstaked][account][external_storage][drop] - AssertionError: assert -32521 == <RPCErrorCode.BANNED_OPCODE: -32502>
 +  where -32521 = Error(code=-32521, message='execution reverted', data=None, id=163).code
FAILED tests/bundle/test_storage_rules.py::test_rule[staked][account][no_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=165)
FAILED tests/bundle/test_storage_rules.py::test_rule[staked][account][account_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=167)
FAILED tests/bundle/test_storage_rules.py::test_rule[staked][account][account_reference_storage][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=169)
FAILED tests/bundle/test_storage_rules.py::test_rule[staked][account][account_reference_storage_struct][ok] - Exception: expected result object, got:
Error(code=-32521, message='execution reverted', data=None, id=171)
FAILED tests/bundle/test_storage_rules.py::test_rule[staked][account][external_storage][drop] - AssertionError: assert -32521 == <RPCErrorCode.BANNED_OPCODE: -32502>
 +  where -32521 = Error(code=-32521, message='execution reverted', data=None, id=173).code
============ 10 failed, 104 passed, 1 skipped, 4 warnings in 28.27s ============
